import React from 'react';
import { 
  CheckCircle2, 
  Sparkles, 
  Layers, 
  ArrowDown, 
  Clock, 
  XCircle, 
  ShieldAlert,
  Percent
} from 'lucide-react';
import type { CNMCStandardizationAnalyticsResponse } from '../../types';

interface CNMCStandardizationViewProps {
  data: CNMCStandardizationAnalyticsResponse | null;
  loading: boolean;
}

export const CNMCStandardizationView: React.FC<CNMCStandardizationViewProps> = ({
  data,
  loading
}) => {
  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-primary-600"></div>
        <span className="ml-3 text-sm text-gray-500 font-medium">Computing CNMC Standardization Analytics...</span>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="p-8 text-center bg-gray-50 rounded-xl border border-gray-200">
        <p className="text-gray-500 text-sm">No CNMC standardization data available.</p>
      </div>
    );
  }

  const funnelSteps = [
    {
      step: 1,
      title: '1. Ingested Multi-CPSE Materials',
      count: data.funnel.stage_1_raw_materials,
      pct: '100%',
      desc: 'Raw catalog items across participating enterprise ERPs',
      color: 'bg-slate-100 text-slate-800 border-slate-300'
    },
    {
      step: 2,
      title: '2. Duplicate / Match Pairs Identified',
      count: data.funnel.stage_2_duplicate_matches,
      pct: `${((data.funnel.stage_2_duplicate_matches / Math.max(1, data.funnel.stage_1_raw_materials)) * 100).toFixed(1)}%`,
      desc: 'Material pairs identified with similarity &ge; threshold',
      color: 'bg-indigo-50 text-indigo-800 border-indigo-200'
    },
    {
      step: 3,
      title: '3. CNMC Candidate Pipeline',
      count: data.funnel.stage_3_cnmc_candidates,
      pct: `${((data.funnel.stage_3_cnmc_candidates / Math.max(1, data.funnel.stage_1_raw_materials)) * 100).toFixed(1)}%`,
      desc: 'Recommended candidate codes generated by Rule/LLM engine',
      color: 'bg-purple-50 text-purple-800 border-purple-200'
    },
    {
      step: 4,
      title: '4. Governed Master CNMCs Created',
      count: data.funnel.stage_4_approved_masters,
      pct: `${((data.funnel.stage_4_approved_masters / Math.max(1, data.funnel.stage_3_cnmc_candidates)) * 100).toFixed(1)}% of candidates`,
      desc: 'Standard codes formally approved by governance review',
      color: 'bg-emerald-50 text-emerald-800 border-emerald-300'
    },
    {
      step: 5,
      title: '5. Raw Item Mappings Active',
      count: data.funnel.stage_5_active_mappings,
      pct: `${data.mapping_coverage_percentage.toFixed(1)}% catalog coverage`,
      desc: 'Enterprise line items mapped to standardized Master CNMCs',
      color: 'bg-teal-50 text-teal-800 border-teal-300'
    }
  ];

  return (
    <div className="space-y-6">
      {/* Disclaimer Banner */}
      <div className="p-4 rounded-xl border border-blue-200 bg-blue-50/70 text-blue-900 flex items-start gap-3 shadow-xs">
        <ShieldAlert className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
        <div className="text-xs">
          <span className="font-semibold uppercase tracking-wider block text-blue-800">
            Standardization Governance Boundary
          </span>
          <p className="mt-1 text-blue-700 leading-relaxed">
            All CNMC codes reflect the <em>MVP Prototype CNMC Reference Format</em> for demonstration and governance testing.
            Candidate approval requires explicit human governance review in Phase 8 workflows.
          </p>
        </div>
      </div>

      {/* Conversion Funnel */}
      <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-xs">
        <h3 className="text-base font-bold text-gray-900 mb-1">Standardization Conversion Funnel</h3>
        <p className="text-xs text-gray-500 mb-6">From raw heterogeneous ERP items to governed common material codes</p>

        <div className="space-y-3">
          {funnelSteps.map((step, idx) => (
            <React.Fragment key={step.step}>
              <div className={`p-4 rounded-xl border ${step.color} flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 shadow-xs`}>
                <div>
                  <h4 className="text-xs font-bold">{step.title}</h4>
                  <p className="text-xs opacity-80 mt-0.5">{step.desc}</p>
                </div>
                <div className="flex items-center gap-4 text-right">
                  <div>
                    <div className="text-lg font-bold">{step.count.toLocaleString()}</div>
                    <div className="text-[11px] font-semibold opacity-75">{step.pct}</div>
                  </div>
                </div>
              </div>
              {idx < funnelSteps.length - 1 && (
                <div className="flex justify-center my-1">
                  <ArrowDown className="w-4 h-4 text-gray-400" />
                </div>
              )}
            </React.Fragment>
          ))}
        </div>
      </div>

      {/* Candidate Pipeline & Master Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Candidate Pipeline Status */}
        <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-xs space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-gray-100">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-purple-600" />
              <h4 className="text-sm font-bold text-gray-900">CNMC Candidate Pipeline</h4>
            </div>
            <span className="text-xs font-bold text-purple-700 bg-purple-50 px-2 py-0.5 rounded">
              {data.candidate_pipeline.total_candidates} Total
            </span>
          </div>

          <div className="grid grid-cols-3 gap-3 text-center">
            <div className="p-3 bg-amber-50/70 border border-amber-200 rounded-lg">
              <div className="flex items-center justify-center gap-1 text-amber-600 mb-1">
                <Clock className="w-3.5 h-3.5" />
                <span className="text-[11px] font-bold uppercase">Pending</span>
              </div>
              <div className="text-lg font-bold text-amber-900">{data.candidate_pipeline.pending_candidates}</div>
              <div className="text-[10px] text-amber-700 mt-0.5">Awaiting Review</div>
            </div>

            <div className="p-3 bg-emerald-50/70 border border-emerald-200 rounded-lg">
              <div className="flex items-center justify-center gap-1 text-emerald-600 mb-1">
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span className="text-[11px] font-bold uppercase">Approved</span>
              </div>
              <div className="text-lg font-bold text-emerald-900">{data.candidate_pipeline.approved_candidates}</div>
              <div className="text-[10px] text-emerald-700 mt-0.5">Published to Master</div>
            </div>

            <div className="p-3 bg-rose-50/70 border border-rose-200 rounded-lg">
              <div className="flex items-center justify-center gap-1 text-rose-600 mb-1">
                <XCircle className="w-3.5 h-3.5" />
                <span className="text-[11px] font-bold uppercase">Rejected</span>
              </div>
              <div className="text-lg font-bold text-rose-900">{data.candidate_pipeline.rejected_candidates}</div>
              <div className="text-[10px] text-rose-700 mt-0.5">Discarded / Invalid</div>
            </div>
          </div>

          <div className="p-3 bg-gray-50 rounded-lg text-xs space-y-1">
            <div className="flex justify-between">
              <span className="text-gray-500">Pipeline Conversion Rate:</span>
              <span className="font-bold text-emerald-700">
                {data.candidate_pipeline.total_candidates > 0
                  ? `${((data.candidate_pipeline.approved_candidates / data.candidate_pipeline.total_candidates) * 100).toFixed(1)}%`
                  : '0.0%'}
              </span>
            </div>
          </div>
        </div>

        {/* Master Catalog & Mapping Coverage */}
        <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-xs space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-gray-100">
            <div className="flex items-center gap-2">
              <Layers className="w-4 h-4 text-teal-600" />
              <h4 className="text-sm font-bold text-gray-900">Master Catalog & Mapping Coverage</h4>
            </div>
            <span className="text-xs font-bold text-teal-700 bg-teal-50 px-2 py-0.5 rounded">
              {data.master_stats.total_master_codes} Codes
            </span>
          </div>

          <div className="space-y-3">
            <div>
              <div className="flex justify-between text-xs text-gray-600 mb-1">
                <span>Enterprise Line Item Coverage</span>
                <span className="font-bold text-teal-700">{data.mapping_coverage_percentage.toFixed(1)}%</span>
              </div>
              <div className="w-full bg-gray-100 rounded-full h-2.5 overflow-hidden">
                <div 
                  className="bg-teal-500 h-2.5 rounded-full transition-all" 
                  style={{ width: `${Math.min(100, data.mapping_coverage_percentage)}%` }}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3 pt-2">
              <div className="p-3 bg-gray-50 rounded-lg">
                <span className="text-[11px] text-gray-500 font-medium">Active Master Codes</span>
                <div className="text-base font-bold text-gray-900 mt-1">{data.master_stats.active_master_codes}</div>
              </div>
              <div className="p-3 bg-gray-50 rounded-lg">
                <span className="text-[11px] text-gray-500 font-medium">Mapped Line Items</span>
                <div className="text-base font-bold text-gray-900 mt-1">{data.master_stats.total_mapped_line_items}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
