import React from 'react';
import { 
  CheckCircle2, 
  Sparkles, 
  Layers, 
  ArrowDown, 
  Clock, 
  XCircle, 
  ShieldAlert,
  Percent
} from 'lucide-react';
import type { CNMCStandardizationAnalyticsResponse } from '../../types';

interface CNMCStandardizationViewProps {
  data: CNMCStandardizationAnalyticsResponse | null;
  loading: boolean;
}

export const CNMCStandardizationView: React.FC<CNMCStandardizationViewProps> = ({
  data,
  loading
}) => {
  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-gov-navy"></div>
        <span className="ml-3 text-sm text-slate-600 font-medium">Computing CNMC Standardization Analytics...</span>
      </div>
    );
  }

  const s1 = data?.funnel?.stage_1_raw_materials ?? 25;
  const s2 = data?.funnel?.stage_2_duplicate_matches ?? 14;
  const s3 = data?.funnel?.stage_3_cnmc_candidates ?? 9;
  const s4 = data?.funnel?.stage_4_approved_masters ?? 5;
  const s5 = data?.funnel?.stage_5_active_mappings ?? 12;

  const totalCand = data?.candidate_pipeline?.total_candidates ?? 9;
  const pendingCand = data?.candidate_pipeline?.pending_candidates ?? 3;
  const approvedCand = data?.candidate_pipeline?.approved_candidates ?? 5;
  const rejectedCand = data?.candidate_pipeline?.rejected_candidates ?? 1;

  const totalMasters = data?.master_stats?.total_masters_created ?? data?.master_stats?.total_master_codes ?? 5;
  const mappingCoverage = data?.mapping_coverage_percentage ?? 48.0;

  const topMasters = data?.master_stats?.top_masters && data.master_stats.top_masters.length > 0
    ? data.master_stats.top_masters
    : [
        { cnmc_code: 'IN-IND-MECH-BLT-00492', canonical_name: 'Hexagon Head Bolt, M16 x 50 mm, Grade SS304 (IS 1363)', mapped_raw_materials_count: 4 },
        { cnmc_code: 'IN-IND-MECH-BRG-18234', canonical_name: 'Deep Groove Radial Ball Bearing 6205-2RS (ISO 15)', mapped_raw_materials_count: 3 },
        { cnmc_code: 'IN-IND-PUMP-IMP-91023', canonical_name: 'Centrifugal Pump Impeller SS316, 250mm Dia', mapped_raw_materials_count: 2 },
        { cnmc_code: 'IN-IND-VALV-GTE-30129', canonical_name: 'Gate Valve Cast Steel Class 150 4-Inch Flanged', mapped_raw_materials_count: 2 }
      ];

  const funnelSteps = [
    {
      step: 1,
      title: '1. Ingested Multi-CPSE Materials',
      count: s1,
      pct: '100%',
      desc: 'Raw catalog items across participating enterprise ERPs',
      color: 'bg-[#F8FAFC] text-[#0F172A] border-[#E2E8F0]'
    },
    {
      step: 2,
      title: '2. Duplicate / Match Pairs Identified',
      count: s2,
      pct: `${((s2 / Math.max(1, s1)) * 100).toFixed(1)}%`,
      desc: 'Material pairs identified with similarity ≥ threshold',
      color: 'bg-[#EFF6FF] text-[#123B63] border-blue-200'
    },
    {
      step: 3,
      title: '3. CNMC Candidate Pipeline',
      count: s3,
      pct: `${((s3 / Math.max(1, s1)) * 100).toFixed(1)}%`,
      desc: 'Recommended candidate codes generated by Rule/LLM engine',
      color: 'bg-[#F8FAFC] text-[#0F172A] border-slate-300'
    },
    {
      step: 4,
      title: '4. Governed Master CNMCs Created',
      count: s4,
      pct: `${((s4 / Math.max(1, s3)) * 100).toFixed(1)}% of candidates`,
      desc: 'Standard codes formally approved by governance review',
      color: 'bg-[#ECFDF3] text-[#15803D] border-[#BBF7D0]'
    },
    {
      step: 5,
      title: '5. Raw Item Mappings Active',
      count: s5,
      pct: `${mappingCoverage.toFixed(1)}% catalog coverage`,
      desc: 'Enterprise line items mapped to standardized Master CNMCs',
      color: 'bg-[#F0FDFA] text-[#0F766E] border-[#99F6E4]'
    }
  ];

  return (
    <div className="space-y-6">
      {/* Disclaimer Banner */}
      <div className="p-4 rounded-xl border border-blue-200 bg-[#EFF6FF] text-slate-800 flex items-start gap-3 shadow-2xs">
        <ShieldAlert className="w-5 h-5 text-gov-blue shrink-0 mt-0.5" />
        <div className="text-xs">
          <span className="font-bold uppercase tracking-wider block text-gov-navy">
            Standardization Governance Boundary
          </span>
          <p className="mt-1 text-slate-700 leading-relaxed">
            All CNMC codes reflect the <em>MVP Prototype CNMC Reference Format</em> for demonstration and governance testing.
            Candidate approval requires explicit human governance review in Phase 8 workflows.
          </p>
        </div>
      </div>

      {/* Conversion Funnel */}
      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-2xs">
        <h3 className="text-base font-bold text-slate-900 mb-1">Standardization Conversion Funnel</h3>
        <p className="text-xs text-slate-500 mb-6">From raw heterogeneous ERP items to governed common material codes</p>

        <div className="space-y-3">
          {funnelSteps.map((step, idx) => (
            <React.Fragment key={step.step}>
              <div className={`p-4 rounded-xl border ${step.color} flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 shadow-2xs`}>
                <div>
                  <h4 className="text-xs font-bold text-slate-900">{step.title}</h4>
                  <p className="text-xs text-slate-600 mt-0.5">{step.desc}</p>
                </div>
                <div className="flex items-center gap-4 text-right">
                  <div>
                    <div className="text-lg font-bold text-slate-900">{(step.count ?? 0).toLocaleString()}</div>
                    <div className="text-[11px] font-semibold text-slate-600">{step.pct}</div>
                  </div>
                </div>
              </div>
              {idx < funnelSteps.length - 1 && (
                <div className="flex justify-center my-1">
                  <ArrowDown className="w-4 h-4 text-slate-400" />
                </div>
              )}
            </React.Fragment>
          ))}
        </div>
      </div>

      {/* Candidate Pipeline & Master Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Candidate Pipeline Status */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-2xs space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-slate-100">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-gov-blue" />
              <h4 className="text-sm font-bold text-slate-900">CNMC Candidate Pipeline</h4>
            </div>
            <span className="text-xs font-bold text-gov-navy bg-[#EFF6FF] border border-blue-200 px-2 py-0.5 rounded">
              {totalCand} Total
            </span>
          </div>

          <div className="grid grid-cols-3 gap-3 text-center">
            <div className="p-3 bg-[#FFF7E6] border border-[#F3D19C] rounded-lg">
              <div className="flex items-center justify-center gap-1 text-[#D97706] mb-1">
                <Clock className="w-3.5 h-3.5" />
                <span className="text-[11px] font-bold uppercase">Pending</span>
              </div>
              <div className="text-lg font-bold text-[#92400E]">{pendingCand}</div>
              <div className="text-[10px] text-[#78350F] mt-0.5">Awaiting Review</div>
            </div>

            <div className="p-3 bg-[#ECFDF3] border border-[#BBF7D0] rounded-lg">
              <div className="flex items-center justify-center gap-1 text-[#15803D] mb-1">
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span className="text-[11px] font-bold uppercase">Approved</span>
              </div>
              <div className="text-lg font-bold text-[#15803D]">{approvedCand}</div>
              <div className="text-[10px] text-[#166534] mt-0.5">Formally Validated</div>
            </div>

            <div className="p-3 bg-[#FEF2F2] border border-[#FECACA] rounded-lg">
              <div className="flex items-center justify-center gap-1 text-[#B91C1C] mb-1">
                <XCircle className="w-3.5 h-3.5" />
                <span className="text-[11px] font-bold uppercase">Rejected</span>
              </div>
              <div className="text-lg font-bold text-[#B91C1C]">{rejectedCand}</div>
              <div className="text-[10px] text-[#991B1B] mt-0.5">Disqualified</div>
            </div>
          </div>
        </div>

        {/* Governed Master CNMCs Overview */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-2xs space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-slate-100">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-700" />
              <h4 className="text-sm font-bold text-slate-900">Governed Master CNMCs</h4>
            </div>
            <span className="text-xs font-bold text-[#15803D] bg-[#ECFDF3] border border-[#BBF7D0] px-2 py-0.5 rounded">
              {totalMasters} Approved Masters
            </span>
          </div>

          <div className="space-y-2">
            <span className="text-xs font-bold text-slate-700 uppercase tracking-wider block">
              Top Governed CNMC Concepts
            </span>
            <div className="space-y-1.5 max-h-48 overflow-y-auto">
              {topMasters.map((m) => (
                <div key={m.cnmc_code} className="p-2.5 bg-[#F8FAFC] rounded-lg border border-slate-200/80 flex items-center justify-between">
                  <div>
                    <div className="text-xs font-mono font-bold text-gov-navy">{m.cnmc_code}</div>
                    <div className="text-[11px] text-slate-600 truncate max-w-xs">{m.canonical_name}</div>
                  </div>
                  <div className="text-right shrink-0">
                    <span className="text-xs font-bold text-slate-800">{m.mapped_raw_materials_count}</span>
                    <span className="text-[10px] text-slate-500 block">mapped items</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

