import React from 'react';
import { LegalPageLayout } from './LegalPageLayout';
import { ShieldCheck, Database, KeyRound, Server, Eye, FileText, RefreshCw, AlertTriangle } from 'lucide-react';

export const PrivacyPolicyPage: React.FC = () => {
  return (
    <LegalPageLayout
      title="Privacy Policy"
      subtitle="Comprehensive data governance and privacy disclosure for the National Unified Material Master Framework."
      categoryBadge="Data Governance & Privacy"
      lastUpdated="September 2026"
    >
      {/* 1. Overview */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <ShieldCheck className="w-5 h-5 text-[#1E3A8A]" />
          <h2>1. Overview & Purpose</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          The <strong>National Unified Material Master Framework</strong> is an enterprise platform developed for the 
          Ministry of Heavy Industries and Department of Public Enterprises, Government of India. The platform facilitates 
          cross-CPSE (Central Public Sector Enterprise) material catalog deduplication, intelligent codification (CNMC), 
          procurement harmonization, and governance audit trails. This Privacy Policy details how data is handled within 
          this portal.
        </p>
      </section>

      {/* 2. Information Handled by the Portal */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <Database className="w-5 h-5 text-[#1E3A8A]" />
          <h2>2. Information Handled by the Portal</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          The portal processes enterprise material records and administrative operational information, including:
        </p>
        <ul className="list-disc pl-5 text-xs sm:text-[13px] text-[#475569] space-y-1.5 leading-relaxed">
          <li><strong>Material Master Records:</strong> Item codes, standardized item descriptions, technical parameters, unit of measurement (UOM), UNSPSC classifications, and manufacturer part numbers uploaded by participating CPSEs (e.g., IOCL, ONGC, NTPC, SAIL, CIL).</li>
          <li><strong>Enterprise User Profiles:</strong> Authorized enterprise email addresses, organizational entity affiliations, assigned role designations (National Master Admin, CPSE Material Manager, Domain Reviewer, National Auditor), and associated system timestamps.</li>
          <li><strong>Governance Audit Decision Logs:</strong> Formal approval, rejection, and modification logs generated by authorized reviewers during catalog codification workflows.</li>
        </ul>
      </section>

      {/* 3. Authentication & Session Information */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <KeyRound className="w-5 h-5 text-[#1E3A8A]" />
          <h2>3. Authentication & Session Information</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          User authentication is verified through a cryptographically signed <strong>JWT Bearer Token (HS256)</strong> issued upon credential verification. 
          The access token is stored locally within the browser&apos;s <code>localStorage</code> (<code>auth_token</code>) to maintain session state across requests. 
          The portal does not collect external social identifiers or biometric data.
        </p>
        <div className="p-3.5 bg-[#F0FDF4] border border-[#BBF7D0] rounded-xl text-xs text-[#166534] flex items-start gap-2.5">
          <ShieldCheck className="w-4 h-4 text-[#15803D] shrink-0 mt-0.5" />
          <span>
            <strong>Demonstration Credentials Notice:</strong> Pre-configured demo accounts (e.g., <code>national_admin@sih.demo</code>, <code>cpse_manager_a@sih.demo</code>) operate on seeded evaluation data for demonstration purposes.
          </span>
        </div>
      </section>

      {/* 4. How Information is Used */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <Server className="w-5 h-5 text-[#1E3A8A]" />
          <h2>4. How Information is Used</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          Data ingested and processed within the portal is utilized strictly for institutional operations:
        </p>
        <ul className="list-disc pl-5 text-xs sm:text-[13px] text-[#475569] space-y-1.5 leading-relaxed">
          <li><strong>Semantic Similarity & Deduplication:</strong> High-dimensional vector embeddings generated to detect cross-CPSE duplicate material definitions.</li>
          <li><strong>Catalog Standardization:</strong> Mapping proprietary CPSE item codes to the unified National Common Material Code (CNMC).</li>
          <li><strong>Procurement Opportunity Analysis:</strong> Macro-level aggregation of demand patterns to optimize public procurement and inventory rationalization.</li>
          <li><strong>Regulatory Auditability:</strong> Maintaining immutable chronological trails of all catalog ingestion and domain review resolutions.</li>
        </ul>
      </section>

      {/* 5. Data Sharing & Boundaries */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <Eye className="w-5 h-5 text-[#1E3A8A]" />
          <h2>5. Data Sharing & Access Boundaries</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          Information within the portal is accessible solely to authorized enterprise personnel based on <strong>Role-Based Access Control (RBAC)</strong> Layer 1 boundaries:
        </p>
        <ul className="list-disc pl-5 text-xs sm:text-[13px] text-[#475569] space-y-1.5 leading-relaxed">
          <li><strong>Tenant Isolation:</strong> CPSE Material Managers possess operational authority bounded to their designated organization.</li>
          <li><strong>National Oversight:</strong> National Master Admins, Domain Reviewers, and Auditors receive scoped visibility for standardization governance.</li>
          <li><strong>No Commercial Monetization:</strong> No data is sold, rented, or distributed to third-party commercial brokers or external advertising networks.</li>
        </ul>
      </section>

      {/* 6. Cookies & Client-Side Storage */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <FileText className="w-5 h-5 text-[#1E3A8A]" />
          <h2>6. Cookies & Client-Side Storage</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          This portal does <strong>not</strong> employ third-party advertising cookies, marketing pixels, or commercial telemetry beacons. 
          Browser client storage is utilized exclusively for:
        </p>
        <ul className="list-disc pl-5 text-xs sm:text-[13px] text-[#475569] space-y-1 text-xs sm:text-[13px]">
          <li><code>localStorage.auth_token</code> — Cryptographic JWT authentication token used to verify authorization with backend API endpoints.</li>
        </ul>
      </section>

      {/* 7. Security Measures */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <ShieldCheck className="w-5 h-5 text-[#1E3A8A]" />
          <h2>7. Security Measures</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          Security controls implemented in the system architecture include:
        </p>
        <ul className="list-disc pl-5 text-xs sm:text-[13px] text-[#475569] space-y-1.5 leading-relaxed">
          <li><strong>Encrypted Communications:</strong> Enforced HTTPS/TLS cryptographic transport protocols.</li>
          <li><strong>Strict RBAC Enforcement:</strong> API-level permission gates on all data ingestion, mapping, and governance endpoints.</li>
          <li><strong>Statutory Audit Trail:</strong> Append-oriented logging of operational transactions and governance reviews.</li>
        </ul>
      </section>

      {/* 8. Policy Updates & Support */}
      <section className="space-y-3">
        <div className="flex items-center gap-2 text-base font-bold text-[#0F172A]">
          <RefreshCw className="w-5 h-5 text-[#1E3A8A]" />
          <h2>8. Updates & Administrative Inquiries</h2>
        </div>
        <p className="text-xs sm:text-[13px] text-[#475569] leading-relaxed">
          This policy may be amended periodically to reflect updates in national standardization directives or enterprise security controls. 
          Authorized representatives with inquiries regarding data governance should contact the designated portal administrator through official institutional support channels.
        </p>
      </section>
    </LegalPageLayout>
  );
};
